import { lazy } from "react";

export const lazyPages = Object.freeze({
  Landing: lazy(() => import("@/pages/Landing")),
  BookAccount: lazy(() => import("@/pages/BookAccount")),
  About: lazy(() => import("@/pages/About")),
  Contact: lazy(() => import("@/pages/Contact")),
  Terms: lazy(() => import("@/pages/Terms")),
  GuestBooking: lazy(() => import("@/pages/GuestBooking")),
  ProfileSetup: lazy(() => import("@/pages/ProfileSetup")),
  PortalSettings: lazy(() => import("@/pages/PortalSettings")),
  PortalAccount: lazy(() => import("@/pages/PortalAccount")),
  Store: lazy(() => import("@/pages/Store")),
  Login: lazy(() => import("@/pages/Login")),
  Register: lazy(() => import("@/pages/Register")),
  ForgotPassword: lazy(() => import("@/pages/ForgotPassword")),
  ResetPassword: lazy(() => import("@/pages/ResetPassword")),
  OAuthConsent: lazy(() => import("@/pages/OAuthConsent")),
  FeedbackRating: lazy(() => import("@/pages/FeedbackRating")),
  PublicTrack: lazy(() => import("@/pages/PublicTrack")),
  Overview: lazy(() => import("@/pages/dashboard/Overview")),
  Jobs: lazy(() => import("@/pages/dashboard/Jobs")),
  Calendar: lazy(() => import("@/pages/dashboard/Calendar")),
  Invoices: lazy(() => import("@/pages/dashboard/Invoices")),
  Parts: lazy(() => import("@/pages/dashboard/Parts")),
  AdminFeedback: lazy(() => import("@/pages/admin/AdminFeedback")),
  AdminClients: lazy(() => import("@/pages/admin/AdminClients")),
  AdminActivityLog: lazy(() => import("@/pages/admin/AdminActivityLog")),
  SystemSettings: lazy(() => import("@/pages/settings/SystemSettings")),
  ServicePricingAdmin: lazy(() => import("@/pages/settings/ServicePricingAdmin")),
  SystemHealth: lazy(() => import("@/pages/settings/SystemHealth")),
  AssetManagement: lazy(() => import("@/pages/AssetManagement")),
  ServicePricing: lazy(() => import("@/pages/ServicePricing")),
  BlogIndex: lazy(() => import("@/pages/blog/BlogIndex")),
  BlogPostPage: lazy(() => import("@/pages/blog/BlogPostPage")),
  BlogCategoryPage: lazy(() => import("@/pages/blog/BlogCategoryPage")),
  BlogTagPage: lazy(() => import("@/pages/blog/BlogTagPage")),
  BlogDashboard: lazy(() => import("@/pages/blog-admin/BlogDashboard")),
  BlogPosts: lazy(() => import("@/pages/blog-admin/BlogPosts")),
  BlogEditor: lazy(() => import("@/pages/blog-admin/BlogEditor")),
  BlogGenerator: lazy(() => import("@/pages/blog-admin/BlogGenerator")),
  BlogTaxonomy: lazy(() => import("@/pages/blog-admin/BlogTaxonomy")),
  BlogSettings: lazy(() => import("@/pages/blog-admin/BlogSettings")),
  BlogLogs: lazy(() => import("@/pages/blog-admin/BlogLogs")),
});

