// Extensive list of e-scooter brands and their popular models for the booking form.
// Updated June 2026 from: scooterhut.com.au, iscoot.com.au, rideelectric.com.au
export const SCOOTER_BRANDS = {
  // --- HIGH POPULARITY / COMMON IN AU MARKET ---
  Segway: [
    "Ninebot C2 Pro",
    "Ninebot MAX G2",
    "Ninebot MAX G2D",
    "Ninebot MAX G3",
    "Ninebot MAX G30",
    "Ninebot MAX G30LP",
    "Ninebot MAX G65",
    "Ninebot F2 Plus",
    "Ninebot F2 Pro",
    "Ninebot F25",
    "Ninebot F40",
    "Ninebot E2",
    "Ninebot E45",
    "Ninebot GT1E",
    "Ninebot GT2 Pro",
    "Ninebot GT3 Pro",
    "Ninebot P65",
    "Ninebot P100S",
    "Ninebot ZT3 Pro",
    "Ninebot D18W",
    "Other model",
  ],
  Kaabo: [
    "Mantis Urban",
    "Mantis 10",
    "Mantis 10 Plus V2",
    "Mantis Duo 10 V2",
    "Mantis King GT",
    "Wolf Warrior",
    "Wolf Warrior X",
    "Wolf Warrior X Plus",
    "Wolf Warrior X Max",
    "Wolf King",
    "Wolf King GT",
    "Wolf King GT Pro",
    "Other model",
  ],
  Dualtron: [
    "Dualtron Mini",
    "Dualtron Mini V2",
    "Dualtron Victor",
    "Dualtron Victor S",
    "Dualtron Spider",
    "Dualtron Eagle Pro",
    "Dualtron Storm",
    "Dualtron Thunder 2",
    "Dualtron Thunder 3",
    "Dualtron Ultra 2",
    "Dualtron X",
    "Dualtron X2",
    "Other model",
  ],
  NIU: [
    "KQi1 Pro",
    "KQi3 Pro",
    "KQi3 Max",
    "KQi2 Pro",
    "KQi 300P",
    "KQi 300X",
    "KQi Air",
    "Other model",
  ],
  Pure: [
    "Pure Air",
    "Pure Air Pro",
    "Pure Air3",
    "Pure Air3 Pro",
    "Pure Air4",
    "Pure Air4 Pro",
    "Pure Air5",
    "Pure Air5 Pro+ Suspension",
    "Pure Advance",
    "Pure Advance Flex",
    "Pure x McLaren 2025",
    "Other model",
  ],
  INMOTION: [
    "S1",
    "V11",
    "V12",
    "V13",
    "V14",
    "RS",
    "RS Lite",
    "Other model",
  ],
  Vsett: [
    "Vsett 8",
    "Vsett 8+",
    "Vsett 8 APEX",
    "Vsett 9 APEX",
    "Vsett 10 Light",
    "Vsett 10 APEX",
    "Vsett 10+",
    "Vsett 11+",
    "Vsett 11+ Super",
    "Other model",
  ],
  Zero: [
    "Zero 8",
    "Zero 8 Plus",
    "Zero 9",
    "Zero 10",
    "Zero 10X",
    "Zero 11X",
    "Other model",
  ],
  Xiaomi: [
    "Mi Electric Scooter 4",
    "Mi 4 Pro",
    "Mi 4 Ultra",
    "Mi 4 Lite",
    "Mi 3",
    "Mi Pro 2",
    "Mi Pro",
    "Mi Essential",
    "Mi 1S",
    "Mi M365",
    "Other model",
  ],
  Nami: [
    "Nami Burn-E",
    "Nami Burn-E 2",
    "Nami Klima",
    "Nami Klima Max",
    "Other model",
  ],
  Inokim: [
    "Inokim OX",
    "Inokim OXO",
    "Inokim Quick 4",
    "Inokim Quick",
    "Inokim Light",
    "Inokim Light 2",
    "Inokim Super Quick",
    "Other model",
  ],
  // --- OTHER BRANDS SOLD IN AU ---
  Bexly: [
    "Blackhawk",
    "Storm",
    "Other model",
  ],
  BLVD: [
    "BLVD Cruze",
    "BLVD Elite",
    "BLVD Ranger",
    "BLVD Spark",
    "BLVD Stealth",
    "Other model",
  ],
  VIPPA: [
    "Reapa X1",
    "Reapa Pro",
    "Other model",
  ],
  Mearth: [
    "Mearth GTS",
    "Mearth GTS Max",
    "Mearth GTS Air",
    "Mearth RS",
    "Mearth RS Pro",
    "Mearth S",
    "Mearth S Pro",
    "Mearth Neuron",
    "Other model",
  ],
  Razor: [
    "PowerCore E90",
    "PowerCore E100",
    "E200",
    "E300",
    "E500",
    "EcoSmart",
    "Other model",
  ],
  Evada: [
    "Dash 150",
    "Other model",
  ],
  Apollo: [
    "Apollo City",
    "Apollo City Pro",
    "Apollo Air",
    "Apollo Air Pro",
    "Apollo Ghost",
    "Apollo Phantom",
    "Apollo Pro",
    "Apollo Explore",
    "Other model",
  ],
  Emove: [
    "Emove Cruiser",
    "Emove Cruiser S",
    "Emove RoadRunner",
    "Other model",
  ],
  Unagi: [
    "Model One",
    "Model Eleven",
    "Other model",
  ],
  Fluid: [
    "Fluid Mosquito",
    "Fluid Horizon",
    "Fluid CityRider",
    "Other model",
  ],
  Yadea: [
    "KS5 Pro",
    "ElitePrime",
    "Other model",
  ],
  Gotrax: [
    "GXL V2",
    "G4",
    "GX2",
    "XR Elite",
    "Other model",
  ],
  Hiboy: [
    "S2",
    "S2 Pro",
    "Max",
    "KS4 Pro",
    "Other model",
  ],
  Okai: [
    "ES400",
    "ES800",
    "Neon",
    "Other model",
  ],
  Dragon: [
    "Dragon GTR",
    "Dragon GTS",
    "Dragon GT",
    "Dragon Z",
    "Other model",
  ],
  Turboant: [
    "X7 Pro",
    "M10",
    "V8",
    "Other model",
  ],
  Levy: [
    "Levy Plus",
    "Levy Electric",
    "Other model",
  ],
  Other: [],
};

// Most popular brands first (common in AU), then the rest alphabetically, with "Other" last.
const POPULAR = ["Segway", "Kaabo", "Dualtron", "NIU", "Pure", "INMOTION", "Vsett", "Zero", "Xiaomi", "Nami"];

// Returns true if the chosen model is valid for the chosen brand.
// "Other"/custom brands accept any model; known brands require a model from their list.
export function isModelValidForBrand(make, model) {
  if (!make) return false;
  if (make === "Other") return true;
  const models = SCOOTER_BRANDS[make] || [];
  return models.includes(model);
}

export const BRAND_NAMES = (() => {
  const rest = Object.keys(SCOOTER_BRANDS)
    .filter((b) => b !== "Other" && !POPULAR.includes(b))
    .sort((a, b) => a.localeCompare(b));
  return [...POPULAR, ...rest, "Other"];
})();